### ISSUE TITLE
documentation cleanup for find_AU3

### ISSUE THREAD

**Issue by agupta01** [agupta01/sigmet#3]
https://github.com/agupta01/sigmet/blob/4ee167e0ceaee0368c77c10edadf9eca542caf14/sigmet/au3_functions.py#L308
Is end_date designed to be a cutoff such that the start date can only come before it or after it? Currently unclear in the docs, please fix. 
If end_date filters to only recession start dates prior to it, maybe consider renaming the variable, as there will be situations for which `end_date < start_date` in the method header, which can get confusing to a user.

**Comment by camille-004** [comment]
That variable has to be after start_date; it's essentially indicates how far my_min can go into the set of local minima in finding the start date.

Changed it to cutoff_for_start in the code.
